services:
    aurelienazerty.photos.listener:
        class: aurelienazerty\photos\event\listener
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@user'
            - '@template'
            - '@dispatcher'
            - '@language'
        tags:
            - { name: event.listener }