services:
    Aurelienazerty.Photos.listener:
        class: Aurelienazerty\Photos\event\listener
        arguments:
            - @dbal.conn
            - @config
            - @user
            - @template
            - @dispatcher
        tags:
            - { name: event.listener }
